frontend/modules/catalog/controllers/CartController.php
<?php
namespace frontend\modules\catalog\controllers;


use backend\modules\catalog\models\Care;
use backend\modules\common_data\models\Currency;
use backend\modules\sertificate\models\Sertificate;
use common\helpers\NovaposhtaHelper;
use frontend\models\LoginCartForm;
use frontend\models\LoginForm;
use frontend\models\RegistrationCartForm;
use frontend\modules\catalog\models\OrderContact;
use frontend\modules\catalog\models\OrderForm;
use yii\helpers\Url;
use yii\i18n\Formatter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yz\shoppingcart\ShoppingCart;
use backend\modules\catalog\models\Product;
use frontend\models\RegistrationForm;
use backend\modules\catalog\models\Order;
use Yii;
use yii\widgets\ActiveForm;

class CartController extends Controller
{

    public function actionIndex($type = '')
    {
        $cart = $this->getCart();

        if (empty($cart->getPositions())) {
            Yii::$app->session->remove('promocode');
            Yii::$app->session->remove('promocode_price');
            $this->goHome();
        }

        $data['cart'] = $cart;
        $data['type'] = $type;

        if (\Yii::$app->user->isGuest) {
            if ( $type == 'login' ) {
                $model = new RegistrationCartForm();
                $data['model'] = $model;
            }else {
                $modelLogin = new LoginCartForm();
                $data['modelLogin'] = $modelLogin;
            }
        }

        $modelOrderContact = new OrderContact();

        if ($modelOrderContact->load(\Yii::$app->request->post()) && $modelOrderContact->validate()) {

            $session = Yii::$app->session;

            $order_contact = [
                'name' => $modelOrderContact->name,
                'surname' => $modelOrderContact->surname,
                'phone' => $modelOrderContact->phone,
                'email' => $modelOrderContact->email
            ];

            $session->set('order_contact', $order_contact);

            $this->redirect(Url::to(['/catalog/cart/checkout']));
        }

        $data['modelOrderContact'] = $modelOrderContact;

        return $this->render('index', $data);
    }

    public function actionRegistered($type = '')
    {
        $cart = $this->getCart();


        $data['cart'] = $cart;
        $data['type'] = $type;

        if (\Yii::$app->user->isGuest) {
            if ( $type == 'login' ) {
                $model = new RegistrationCartForm();
                $data['model'] = $model;
            }else {
                $modelLogin = new LoginCartForm();
                $data['modelLogin'] = $modelLogin;
            }
        }

        $modelOrderContact = new OrderContact();

        if ($modelOrderContact->load(\Yii::$app->request->post()) && $modelOrderContact->validate()) {

            $session = Yii::$app->session;

            $order_contact = [
                'name' => $modelOrderContact->name,
                'surname' => $modelOrderContact->surname,
                'phone' => $modelOrderContact->phone,
                'email' => $modelOrderContact->email
            ];

            $session->set('order_contact', $order_contact);

            $this->redirect(Url::to(['/catalog/cart/checkout']));
        }

        $data['modelOrderContact'] = $modelOrderContact;

        return $this->render('registered', $data);
    }

    public function actionCheckout()
    {
        $cart = $this->getCart();

        if (empty($cart->getPositions())) {
            Yii::$app->session->remove('promocode');
            Yii::$app->session->remove('promocode_price');
            $this->goHome();
        }

        $modelOrder = new OrderForm([], $cart);
        $modelOrder->scenario = OrderForm::SCENARIO_DEFAULT;

        if ($modelOrder->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;

            $result = $modelOrder->created();

            if ($result) {
//                $this->redirect(Url::to(['/catalog/cart/finish', 'order_id' => $result['order_id']]));
                return [
                    'status' => true,
                    'redirectUrl' => Url::to(['/catalog/cart/finish', 'order_id' => $result['order_id']]),
                    'result' => $result
                ];
            } else {
                return [
                    'errors' => ActiveForm::validate($modelOrder)
                ];
            }
        }

        $np = new NovaposhtaHelper();
        $warehouses = [];
        $cities = [];

        foreach ($np->np() as $k => $item) {
            $cities[$k] = $k;
        }

        if ($city = \Yii::$app->request->post('city')) {

            foreach ($np->warehouse($city) as $item) {
                $warehouses[] = Yii::t('app', 'Отделение №') . $item['number'] . ' - ' . $item['address'];
            }
//            pr($warehouses);
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            return $this->asJson($warehouses);
        }



        return $this->render('checkout', [
            'cart' => $cart,
            'cities' => $cities,
            'warehouses' => $warehouses,
            'model' => $modelOrder
        ]);
    }
    public function actionNewPricePromo()
    {
        if (Yii::$app->request->isAjax) {
            $promocode = Yii::$app->request->post('field1');
            if(!empty($promocode)){
                $cart = $this->getCart();
                $productInfo = $cart->getPositions();
                $model = new OrderForm([], $this->getCart());
                $sertificate = $model->getSertificateByParam($promocode);
                $new_price = 0;
                if($sertificate){
                    $cost =  $sertificate->cost;
                    foreach($productInfo as $item){
                        $product = $item->getProduct();

                        if (!$product->special) {
                            $new_price += $item->getCost() * ($cost / 100);
                        }
//                        if(isset($product->currentAction)) {
//                            if($model->getRelationSertificate($sertificate->id, $product->category_id, $product->currentAction->action_id)){
//                                $new_price += $item->getCost() * ($cost / 100);
//                            }
//                        }
//                        else{
//                            if($model->getRelationSertificate($sertificate->id, $product->category_id, 1)){
//                                if($product->new_from_date <= time() && $product->new_to_date >= time()){
//
//                                }
//                                else {
//                                    $new_price += $item->getCost() * ($cost / 100);
//                                }
//                            }
//                        }
                    }

                    Yii::$app->session->set('promocode', $promocode);
                    Yii::$app->session->set('promocode_price', $new_price);
                    echo $cart->getCost() - $new_price .' '. Yii::t('currency', Currency::getCurrent()->code);
                }
            }
            exit;
        }
    }

    public function actionFastOrder()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;

            $model= new OrderForm([], $this->getCart());
            $model->scenario = OrderForm::SCENARIO_FAST_ORDER;
            $model->phone = Yii::$app->request->post('phone');
            $result = [];

            if ($model->validate() && $result = $model->created()) {
                $this->setSession($result['order_id']);
                $result = [
                    'status' => true,
                    'redirectUrl' => Url::to(['/catalog/cart/finish', 'order_id' => $result['order_id']])
                ];
            } else {
                $result['errors'] = ActiveForm::validate($model);
            }

            return $result;
        }
    }

    public function actionProfileValidate()
    {
        if (\Yii::$app->user->isGuest) {
            $model = new RegistrationCartForm();
        } else {
            $user = \Yii::$app->user->identity;
            $model = new OrderForm([], $this->getCart());
        }

        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $data['status'] = '';

            $cart_arr = [];
            $i = 0;
            foreach (Yii::$app->cart->getPositions() as $position_item){
                $i++;
                $product = Product::find()->where(['id' => $position_item->id])->one();
                $cart_arr[] = [
                    'id' => $product->code,
                    'price'      => Yii::$app->cart->getProductPrice($position_item->id),
                    'quantity'   => $position_item->getQuantity(),
                    'name'   => str_replace('"', ' ', $product->title),
                    'position'   => $i,
                    'category'   => $product->category->title,
                    'variant' => 'in_stock',
                    'list' => 'Категории товаров/sale',
                    'brand' => 'MustHave'
                ];
            }

            if ($model->validate() && $model->register()){

                $data['currency'] = Currency::getCurrent()['code'];
                $data['products'] = $cart_arr;

                $data['title'] = \Yii::t('cart', 'Вы успешно зарегистрировались');
                $data['text'] = \Yii::t('cart', 'Данные для авторизации высланы на Ваш email');
                $data['status'] = true;


            } else {
                $data['errors'] = ActiveForm::validate($model);
            }

            return $data;
        }
    }

    public function actionLoginValidate()
    {
        $model = new LoginCartForm();

frontend/modules/catalog/views/cart/index/_block_you_order.php
<div class="oform-zacaz-tow-conteiner">
    <?php
    $promocode_price = Yii::$app->session->get('promocode_price');
    ?>
    <div class="oform-zacaz-tow-conteiner_top">
        <h4 class="oform-zacaz-tow-conteiner_top_title"><?= Yii::t('cart', 'Ваш заказ'); ?></h4>
        <a href="" class="linck-redact-zakaz"><?= Yii::t('cart', 'Редактировать заказ'); ?></a>
    </div>

    <div class="oform-zacaz-tow-conteiner_conteiner-towar">
        <?php foreach ($cart->getPositions() as $item): ?>
            <?= $this->render('_product_item', ['item' => $item]) ?>
        <?php endforeach; ?>
    </div>

    <div class="oform-zacaz-tow-conteiner_prise-sales">
        <div class="lins-sale-oform-zakaz">
            <p><?= Yii::t('cart', 'Сумма'); ?>:</p>
            <p><b class="dff335rgg"><?= $cart->getCost() ?> <?= Yii::t('cart', 'грн'); ?></b></p>
        </div>
        <?php if ($promocode_price): ?>
            <div class="lins-sale-oform-zakaz">
                <p><?= Yii::t('cart', 'Скидка по промокоду'); ?>:</p>
                <p><b>-<?= $promocode_price ?> <?= Yii::t('cart', 'грн'); ?></b></p>
            </div>
        <?php endif; ?>
        <!--                <div class="lins-sale-oform-zakaz">-->
        <!--                    <p>Доставка:</p>-->
        <!--                    <p><b>50 грн</b></p>-->
        <!--                </div>-->
    </div>

    <div class="oform-zacaz-tow-conteiner_prise-claster">
        <div class="line-oform-zakaz-prise">
            <p class="texss"><?= Yii::t('cart', 'Всего'); ?>:</p>
            <p class="line-oform-zakaz-prise_prise"><?= $cart->getCost() - $promocode_price ?> <?= Yii::t('cart', 'грн'); ?></p>
        </div>

        <?php if (!$promocode_price): ?>
            <p class="bt-promocod-vvod"><?= Yii::t('cart', 'Ввести промокод'); ?></p>
            <div class="line-vvod-promocod">
                <input type="text" class="inppromocod">
                <div class="help-block"></div>
                <buttod class="bt-promocod-go"><?= Yii::t('cart', 'Применить'); ?></buttod>
            </div>
        <?php endif; ?>
    </div>


</div>

<?php

$this->registerJs("$('.bt-promocod-go').click(function(e){
$('.line-vvod-promocod .help-block').text('');
    $.ajax({
        url: 'cart/new-price-promo',
        type: 'POST',
        data: { field1: $('.inppromocod').val()} ,
        success: function(data) {
            if(data != ''){
                location.reload();
            } else {
                $('.line-vvod-promocod .help-block').text('Промокод неверный');
            }
            
        }
    });
});", \yii\web\View::POS_READY);

?>

frontend/modules/catalog/views/cart/index/_product_item.php
<div class="corzina-tow-box oform-tow-boxs">
    <div class="corzina-tow-box_img">
        <img src="<?= $item->getProduct()->image->path ?>" alt="">
    </div>
    <div class="info-towar-corz">
        <a href="" class="title-info-corz"><?= $item->getProduct()->title ?></a>
        <!--                        <p class="ss2">тиффани блю</p>-->
        <p class="colstyczakaz"><?= $item->quantity ?> <?= Yii::t('cart', 'шт'); ?></p>


    </div>

    <div class="p-prise-corz-tow">
        <p class="jspr-corz"><?= $item->price ?></p>
        <p><?= Yii::t('cart', 'грн'); ?></p>
    </div>
</div>