backend/modules/catalog/models/Action.php
<?php

namespace backend\modules\catalog\models;

use paulzi\jsonBehavior\JsonBehavior;
use Yii;
use common\models\Lang;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;

/**
 * This is the model class for table "action".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $position
 * @property integer $type
 * @property string $key
 * @property string $from_date
 * @property string $to_date
 * @property string $romokod
 *
 * @property ActionLang[] $actionLangs
 * @property ActionLang[] $actionLangs0
 * @property ActionProduct[] $actionProducts
 * @property Product[] $products
 */
class Action extends \yii\db\ActiveRecord
{
    const TYPE_BASE_ACTION = 1;
    const TYPE_GROWING_ACTION = 2;
    const TYPE_COMPLECT = 3;

    const SCENARIO_DEFAULT = 0;
    const SCENARIO_OUTLET = 1;

    const STATUS_ACTIVE = 1;
    const STATUS_NOTACTIVE = 0;
    const SHOW_ON_PAGE = 1;

    public $name;
    protected static $_action;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'action';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => JsonBehavior::className(),
                'attributes' => ['params'],
            ],
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                'slugAttribute' => 'alias',
                'ensureUnique' => true
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'created_at', 'updated_at', 'position', 'type', 'scenario', 'show_on_page'], 'integer'],
            [['from_date', 'to_date'], 'safe'],
            [['key'], 'string', 'max' => 40],
            [['promokod'], 'string', 'max' => 50],
            [['key'], 'unique'],
            [['params', 'title'], 'string'],
            ['alias', 'string', 'max' => '250'],
            ['alias', 'unique'],
            ['type', 'default', 'value' => self::TYPE_BASE_ACTION],
            ['scenario', 'default', 'value' => self::SCENARIO_DEFAULT]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'position' => 'Position',
            'type' => 'Type',
            'key' => 'Key',
            'from_date' => 'From Date',
            'to_date' => 'To Date',
            'promokod' => 'Promokod',
            'scenario' => 'Scenario',
        ];
    }

    public function getLang()
    {
        return $this->hasOne(ActionLang::className(), ['record_id' => 'id'])->where(['lang_id' => Lang::getCurrent()->id]);
    }

    public function getTitle()
    {
        return $this->lang ? $this->lang->title : '';
    }

    public function getDescription()
    {
        return $this->lang ? $this->lang->description : '';
    }

    public function getText()
    {
        return $this->lang ? $this->lang->text : '';
    }

    public function getImage()
    {
        return $this->lang ? $this->lang->image : '';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['id' => 'product_id'])->viaTable('action_product', ['action_id' => 'id']);
    }

    public function getGrowing()
    {
        $this->hasOne(ActionGrowing::className(), ['action_id' => 'id']);
    }

    public static function getStatusList()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('common', 'Активный'),
            self::STATUS_NOTACTIVE => Yii::t('common', 'Неактивный')
        ];
    }

    public function getStatusDetail()
    {
        return isset(self::getStatusList()[$this->status]) ? self::getStatusList()[$this->status] : '';
    }

    public static function getScenarioList()
    {
        return [
            self::SCENARIO_DEFAULT => Yii::t('common', 'Default'),
            self::SCENARIO_OUTLET => Yii::t('common', 'Outlet'),
        ];
    }

    public function getScenarioDetail()
    {
        return isset(self::getScenarioList()[$this->scenario]) ? self::getScenarioList()[$this->scenario] : '';
    }

    public static function getTypeList()
    {
        return [
            self::TYPE_BASE_ACTION => Yii::t('common', 'Обычные акции'),
            self::TYPE_GROWING_ACTION=> Yii::t('common', 'Наростающая'),
            self::TYPE_COMPLECT=> Yii::t('common', 'Комплект'),
        ];
    }

    public function getTypeDetail()
    {
        return isset(self::getTypeList()[$this->type]) ? self::getTypeList()[$this->type] : '';
    }

    public function getCategories()
    {
        $query = Category::find()->distinct('category.id');
        $query->innerJoin('product', 'product.category_id = category.id');
        $query->innerJoin('action_product', 'action_product.product_id = product.id');
        $query->andWhere([ 'action_id' => $this->id]);
        $query->orderBy(['category.position' => SORT_ASC]);
        $query->andWhere(['category.status' => Category::STATUS_ACTIVE]);

        return $query->all();
    }

    public static function actualAction()
    {
        if (self::$_action == null) {
            self::$_action = self::find()
                ->joinWith('lang')
                ->where(['<=', 'from_date', date('Y-m-d')])
                ->andWhere(['>=', 'to_date', date('Y-m-d')])
                ->andWhere(['status' => self::STATUS_ACTIVE])
                ->andWhere(['!=', 'scenario', self::SCENARIO_OUTLET])
                ->orderBy(['position' => SORT_ASC])->all();
        }

        return self::$_action;
    }

    public function getPassed()
    {
        return strtotime($this->to_date) < time() ? true : false;
    }

    public function getUrl()
    {
        return Url::to(['/catalog/product/action', 'alias' => $this->alias]);
    }
}

backend/modules/catalog/controllers/CategoryController.php
<?php

namespace backend\modules\catalog\controllers;

use backend\modules\catalog\models\CategoryLang;
use backend\modules\catalog\models\load\CategoryLoad;
use backend\modules\catalog\models\soap\CareSoap;
use backend\modules\catalog\models\soap\CategorySoap;
use backend\modules\images\models\Image;
use backend\modules\images\models\ImageLang;
use backend\modules\seo\models\Seo;
use backend\modules\seo\models\SeoLang;
use backend\modules\transliterator\services\TransliteratorService;
use common\models\Lang;
use Yii;
use backend\modules\catalog\models\Category;
use backend\modules\catalog\models\rest\Category as CategoryRest;
use backend\modules\catalog\models\CategorySearch;
use yii\base\Model;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for CategorySoap model.
 */
class CategoryController extends Controller
{

    public function actions()
    {
        return [
            'group' => [
                'class' => 'backend\components\GroupAction',
            ],
        ];
    }

    /**
     * Lists all CategorySoap models.
     * @return mixed
     */
    public function actionIndex()
    {
       // print_r(CareSoap::find()->all());

        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CategorySoap model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CategorySoap model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();
        $modelLang = new CategoryLang();
        $modelLang->lang_id = Lang::$current->id;

        if ($model->load(Yii::$app->request->post()) &&
            $modelLang->load(Yii::$app->request->post())) {

            $model->alias = TransliteratorService::transliterate($modelLang->title);

            if (Model::validateMultiple([$model]) && $model->save()) {
                $modelLang->category_id = $model->id;
                $modelLang->save();
                Yii::$app->session->setFlash('success', 'Категория успешно добавлено');

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    /**
     * Updates an existing CategorySoap model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelLang = $model->lang;

        if (!$modelLang) {
            $modelLang = new CategoryLang();
            $modelLang->lang_id = Lang::$current->id;
            $modelLang->category_id = $model->id;
        }

        if ($model->load(Yii::$app->request->post()) &&
            $modelLang->load(Yii::$app->request->post()) &&
            Model::validateMultiple([$model, $modelLang])) {

            if ($model->save() && $modelLang->save()) {
                Yii::$app->session->setFlash('success', 'Категория успешно отредактирована');

                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'modelLang' => $modelLang
            ]);
        }
    }

    public function actionSeo($id)
    {
        $model = $this->findModel($id);

        $seo = $model->seo;
        if (!$seo) {
            $seo = new Seo();
            $seo->table_name = $model::tableName();
            $seo->record_id = $model->primaryKey;
        }

        $seoLang = $seo->lang;
        if (!$seoLang) {
            $seoLang = new SeoLang();
            $seoLang->lang_id = Lang::$current->id;
        }

        if ($seo->load(Yii::$app->request->post()) && $seoLang->load(Yii::$app->request->post())) {
            $seoLang->seo_id = 0;

            if (Model::validateMultiple([$seo, $seoLang]) && $seo->save()) {
                $seoLang->seo_id = $seo->primaryKey;
                $seoLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('seo', [
            'model' => $model,
            'seo' => $seo,
            'seoLang' => $seoLang
        ]);
    }

    public function actionImages($id)
    {
        $model = $this->findModel($id);

        $image = new Image();
        $imageLang = new ImageLang();
        $imageLang->lang_id = Lang::$current->id;

        return $this->render('images', [
            'model' => $model,
            'image' => $image,
            'imageLang' => $imageLang
        ]);
    }

    public function actionImport()
    {
        $modelsRest = CategorySoap::find()->all();

        CategoryLoad::load($modelsRest);

        Yii::$app->session->setFlash('success', 'Данные по категориях импортировано');

        return $this->redirect(['index']);
    }


    /**
     * Deletes an existing CategorySoap model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CategorySoap model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/catalog/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use vova07\imperavi\Widget as ImperaviWidget;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\modules\catalog\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'status')->dropDownList($model->statusList) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'alias')->textInput(['maxlength' => true]) ?>
        </div>
<!--        <div class="col-md-4">-->
<!--            --><?//= $form->field($model, 'key')->textInput(['maxlength' => true]) ?>
<!--        </div>-->
    </div>

    <?= $form->field($modelLang, 'title')->textInput() ?>

<!--    --><?//= $form->field($modelLang, 'description')->widget(ImperaviWidget::className(), [
//        'settings' => [
//            'lang' => 'ru',
//            'minHeight' => 150,
//            'plugins' => [
//                'clips',
//                'fullscreen'
//            ],
//            'imageUpload' => Url::to(['image-upload']),
//            'convertDivs' => false,
//            'replaceDivs' => false
//        ]
//    ]); ?>
<!---->
<!--    --><?//= $form->field($modelLang, 'text')->widget(ImperaviWidget::className(), [
//        'settings' => [
//            'lang' => 'ru',
//            'minHeight' => 150,
//            'plugins' => [
//                'clips',
//                'fullscreen'
//            ],
//            'imageUpload' => Url::to(['image-upload']),
//            'convertDivs' => false,
//            'replaceDivs' => false
//        ]
//    ]); ?>

<!--    --><?//= $form->field($model, 'google_product_category')->textInput() ?>
<!---->
<!--    --><?//= $form->field($model, 'adwords_grouping')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/catalog/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\catalog\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'id') ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'alias') ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'id') ?>
            </div>
        </div>
    <?= $form->field($model, 'id') ?>


    <?= $form->field($model, 'alias') ?>

    <?= $form->field($model, 'position') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/catalog/views/category/_submenu.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Html;

$action = Yii::$app->controller->action->id;
?>
<ul class="nav nav-tabs">
    <li <?= ($action === 'update') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['update', 'id' => $model->primaryKey]) ?>">
            Редактирование
        </a>
    </li>
    <li <?= ($action === 'seo') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['seo', 'id' => $model->primaryKey]) ?>">
            Редактирование SEO
        </a>
    </li>
    <li <?= ($action === 'images') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['images', 'id' => $model->primaryKey]) ?>">
            Редактирование изображений
        </a>
    </li>
</ul>
<br>

backend/modules/catalog/views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\catalog\models\Category */

$this->title = 'Создание категории';
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="">
    <div class="category-create">
        <?= $this->render('_form', [
            'model' => $model,
            'modelLang' => $modelLang
        ]) ?>
    </div>
</div>

backend/modules/catalog/views/category/images.php
<?php
use backend\widgets\ImagesWidget;

$this->title = 'Редактирование категории: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => 'index'];
$this->params['breadcrumbs'][] = ['label' => 'Категория :' . $model->title, 'url' => ['view', 'id' => $model->primaryKey]];
$this->params['breadcrumbs'][] = $this->title
?>
<div class="x_panel">
    <div class="rubric-create">
        <?= $this->render('_submenu', [
            'model' => $model
        ]); ?>

        <?= ImagesWidget::widget([
            'model' => $model,
            'parameters' => [
                'table_name' => $model::tableName()
            ]
        ]); ?>
    </div>
</div>

backend/modules/catalog/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use backend\modules\catalog\models\Category;
use backend\assets\SortTableAsset;


/* @var $this yii\web\View */
/* @var $searchModel backend\modules\catalog\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории';
$this->params['breadcrumbs'][] = $this->title;

\backend\widgets\SortActionWidget::widget(['className' => Category::className()]);
?>
<div class="">
    <div class="category-index">

        <h1>
            <?= Html::a('<i class="fa fa-plus" aria-hidden="true"></i> Добавить категорию', ['create'], ['class' => 'btn btn-success block right']) ?>
<!--            --><?//= Html::a('<i class="fa fa-download" aria-hidden="true"></i> Ипортировать', ['import'], ['class' => 'btn btn-info block right']) ?>
        </h1>
        <div class="pull-right">
            <?=\backend\widgets\GroupActionWidge::widget(['delete' => true, 'activate' => true, 'deactivate' => true, 'className' => Category::className()]) ?>
        </div>
        <?php Pjax::begin(['id' => 'content-list']) ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'class'=>'table table-custom dataTable no-footer',
            'tableOptions'=>['class'=>'table table-custom dataTable no-footer'],
            'columns' => [
                [
                    'class' => 'yii\grid\CheckboxColumn',
                    'contentOptions'=>['style'=>'width: 10px;', 'class' => 'checkbox-item'],
                ],
                [
                    'format' => 'raw',
                    'contentOptions'=>['style'=>'width: 10px;', 'class' => 'sort-item'],
                    'value' => function() {
                        return '<i class="fa fa-arrows-alt"> </i>';
                    }
                ],
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                'alias',
                'updated_at:datetime',
                [
                    'attribute' => 'status',
                    'filter' => $searchModel->getStatusList(),
                    'value' => 'statusDetail'
                ],
                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
</div>

backend/modules/catalog/views/category/seo.php
<?php
use backend\widgets\SeoWidget;

$this->title = 'Редактирование SEO';
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => 'index'];
$this->params['breadcrumbs'][] = ['label' => 'Категория #' . $model->title, 'url' => ['view', 'id' => $model->primaryKey]];
$this->params['breadcrumbs'][] = $this->title
?>

<div class="rubric-create">
    <?= $this->render('_submenu', [
        'model' => $model,
    ]); ?>

    <?= SeoWidget::widget([
        'model' => $seo,
        'modelLang' => $seoLang,
        'owner' => $model
    ]); ?>
</div>

backend/modules/catalog/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\catalog\models\Category */

$this->title = 'Редактирование категории: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="">
    <div class="category-update">
        <?= $this->render('_submenu', [
            'model' => $model,
        ]); ?>

        <?= $this->render('_form', [
            'model' => $model,
            'modelLang' => $modelLang
        ]) ?>
    </div>
</div>

backend/modules/catalog/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\catalog\models\Category */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <p>
        <?= Html::a('Редагувати', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Видалити', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
//            'key',
            'title',
            'description:html',
            'alias',
            'position',
            'updated_at:datetime',
            'created_at:datetime',
            'statusDetail',
            'image.path:image'
        ],
    ]) ?>

</div>