backend/modules/page/models/Category.php
<?php

namespace backend\modules\page\models;

use common\models\Lang;
use Yii;
use backend\modules\page\models\CategoryLang;
use yii\behaviors\SluggableBehavior;
use backend\modules\transliterator\services\TransliteratorService;
use backend\modules\seo\models\Seo;

class Category extends \yii\db\ActiveRecord
{
    const ACTIVE_YES = 1;
    const ACTIVE_NO = 0;

    public static function tableName()
    {
        return 'page_category';
    }

    public function rules()
    {
        return [
            [['parent_id', 'active'], 'integer'],
            [['alias'], 'string', 'max' => 128],
            [['alias'], 'unique'],
            ['alias', 'match', 'pattern' => '/[a-zA-Z0-9-_.]+$/',
                'message' => 'Поле должно содержать только латинские буквы, цифры и дефисы'],
            [['alias', 'parent_id'], 'default', 'value' => null]
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Родительская категория',
            'alias' => 'Alias',
            'active' => 'Активна',
            'title' => 'Заголовок',
            'short_description' => 'Краткое описание',
            'text' => 'Содержимое',
            'subcategories' => 'Подкатегории',
            'pages' => 'Страницы'
        ];
    }

    public function getLang()
    {
        return $this->hasOne(CategoryLang::className(), ['record_id' => 'id'])->where(['lang_id' => Lang::$current->id]);
    }

    public function getTitle()
    {
        return $this->lang ? $this->lang->title : '';
    }

    public function getShort_description()
    {
        return $this->lang ? $this->lang->short_description : '';
    }

    public function getText()
    {
        return $this->lang ? $this->lang->text : '';
    }

    public function getSeo()
    {
        return $this->hasOne(Seo::className(), ['record_id' => 'id'])->where(['table_name' => $this::tableName()]);
    }

    public function getParent()
    {
        return $this->hasOne($this::className(), ['id' => 'parent_id']);
    }

    public function getSubcategories()
    {
        return $this->hasMany($this::className(), ['parent_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        CategoryLang::deleteAll(['record_id' => $this->primaryKey]);
        self::deleteAll(['parent_id' => $this->primaryKey]);
        Page::deleteAll(['category_id' => $this->primaryKey]);
        Seo::deleteAll(['table_name' => $this::tableName(), 'record_id' => $this->primaryKey]);
    }

    public static function getAllActiveProperties()
    {
        return [
            self::ACTIVE_YES => 'Да',
            self::ACTIVE_NO => 'Нет'
        ];
    }

    public function getActiveDetail()
    {
        return isset(self::getAllActiveProperties()[$this->active]) ? self::getAllActiveProperties()[$this->active] : 'Undefined';
    }

    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub

        if (($parent = $this->parent) !== null && !$this->isNewRecord) {
            if ($parent->isParentIsSubcategoryOf($this)) {
                $this->addError('parent_id', 'Нельзя выбрать данную категорию как родительскую');
            }
        }
    }

    protected function isParentIsSubcategoryOf($subcategoryOf)
    {
        $newParent = $this->parent;

        if (!$newParent && $this->id !== $subcategoryOf->id) {
            return false;
        }

        /* @var $newParent Category */
        if ($newParent) {
            if ($newParent->id == $subcategoryOf->id) {
                return true;
            }

            return $newParent->isParentIsSubcategoryOf($subcategoryOf);
        }

        return false;
    }
}

backend/modules/page/controllers/CategoryController.php
<?php

namespace backend\modules\page\controllers;

use backend\modules\accesscontrol\AccessControlFilter;
use backend\modules\page\models\CategorySearch;
use backend\modules\seo\models\Seo;
use backend\modules\seo\models\SeoLang;
use common\models\Lang;
use Yii;
use backend\modules\page\models\CategoryLang;
use yii\base\Model;
use yii\behaviors\SluggableBehavior;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use backend\modules\page\models\Page;
use backend\modules\page\models\Category;
use yii\web\NotFoundHttpException;
use backend\modules\transliterator\services\TransliteratorService;


class CategoryController extends Controller
{

    public function actions()
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => '/uploads/page', // Directory URL address, where files are stored.
                'path' => '@frontend/web/uploads/page' // Or absolute path to directory where files are stored.
            ],
        ];
    }

    /**
     * Lists all CategorySoap models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model = new Category();
        $modelLang = new CategoryLang();
        $modelLang->lang_id = Lang::$current->id;

        $parentId = Yii::$app->request->get('parent');
        if ($parentId) {
            $parent = $this->findModel($parentId);
            $model->parent_id = $parent->primaryKey;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            $modelLang->record_id = 0;

            if (Model::validateMultiple([$model, $modelLang]) && $model->save()) {
                $modelLang->record_id = $model->primaryKey;
                $modelLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => Category::findOne($id),
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelLang = $model->lang;

        if (!$modelLang) {
            $modelLang = new CategoryLang();
            $modelLang->record_id = $model->primaryKey;
            $modelLang->lang_id = Lang::$current->id;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            if (Model::validateMultiple([$model, $modelLang]) && $model->save() && $modelLang->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionDelete($id)
    {
        $category = $this->findModel($id);
        $category->delete();

        return $this->redirect(['index']);
    }

    public function actionSeo($id)
    {
        $model = $this->findModel($id);

        $seo = $model->seo;
        if (!$seo) {
            $seo = new Seo();
            $seo->table_name = $model::tableName();
            $seo->record_id = $model->primaryKey;
        }

        $seoLang = $seo->lang;
        if (!$seoLang) {
            $seoLang = new SeoLang();
            $seoLang->lang_id = Lang::$current->id;
        }

        if ($seo->load(Yii::$app->request->post()) && $seoLang->load(Yii::$app->request->post())) {
            $seoLang->seo_id = 0;

            if (Model::validateMultiple([$seo, $seoLang]) && $seo->save()) {
                $seoLang->seo_id = $seo->primaryKey;
                $seoLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('seo', [
            'model' => $model,
            'seo' => $seo,
            'seoLang' => $seoLang
        ]);
    }

    private function findModel($id)
    {
        $model = Category::findOne($id);

        if (!$model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }
}

backend/modules/page/controllers/PageController.php
<?php

namespace backend\modules\page\controllers;

use backend\modules\accesscontrol\AccessControlFilter;
use backend\modules\images\models\Image;
use backend\modules\images\models\ImageLang;
use backend\modules\page\models\PageLang;
use backend\modules\page\models\PageSearch;
use backend\modules\seo\models\SeoLang;
use common\models\Lang;
use Yii;
use yii\base\Model;
use yii\web\Controller;
use backend\modules\page\models\Page;
use backend\modules\page\models\Category;
use yii\web\NotFoundHttpException;
use backend\modules\seo\models\Seo;
use backend\modules\transliterator\services\TransliteratorService;

class PageController extends Controller
{
    public function actions()
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => '/uploads/page', // Directory URL address, where files are stored.
                'path' => '@frontend/web/uploads/page' // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function actionIndex($category = null)
    {
        $searchModel = new PageSearch();
        $params = Yii::$app->request->queryParams;

        if ($category && !isset(Yii::$app->request->queryParams['PageSearch'])) {
            $params['PageSearch']['category_id'] = (int)$category;
        }

        $dataProvider = $searchModel->search($params);
        $category = $searchModel->category_id ? $this->findCategory($searchModel->category_id) : null;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'category' => $category
        ]);
    }

    public function actionCreate()
    {
        $model = new Page();
        $modelLang = new PageLang();
        $modelLang->lang_id = Lang::$current->id;

        $categoryId = Yii::$app->request->get('category');
        $category = $categoryId ? $this->findCategory($categoryId) : null;
        $model->category_id = $categoryId;

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            $modelLang->record_id = 0;

            if (Model::validateMultiple([$model, $modelLang]) && $model->save()) {
                $modelLang->record_id = $model->primaryKey;
                $modelLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $modelLang = $model->lang;
        if (!$modelLang) {
            $modelLang = new PageLang();
            $modelLang->record_id = $model->primaryKey;
            $modelLang->lang_id = Lang::$current->id;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            if (Model::validateMultiple([$model, $modelLang]) && $model->save() && $modelLang->save()) {
                return $this->redirect(['view', 'id' => $model->primaryKey]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionSeo($id)
    {
        $model = $this->findModel($id);

        $seo = $model->seo;
        if (!$seo) {
            $seo = new Seo();
            $seo->table_name = $model::tableName();
            $seo->record_id = $model->primaryKey;
        }

        $seoLang = $seo->lang;
        if (!$seoLang) {
            $seoLang = new SeoLang();
            $seoLang->lang_id = Lang::$current->id;
        }

        if ($seo->load(Yii::$app->request->post()) && $seoLang->load(Yii::$app->request->post())) {
            $seoLang->seo_id = 0;

            if (Model::validateMultiple([$seo, $seoLang]) && $seo->save()) {
                $seoLang->seo_id = $seo->primaryKey;
                $seoLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('seo', [
            'model' => $model,
            'seo' => $seo,
            'seoLang' => $seoLang
        ]);
    }

    public function actionImages($id)
    {
        $model = $this->findModel($id);

        $image = new Image();
        $imageLang = new ImageLang();
        $imageLang->lang_id = Lang::$current->id;

        return $this->render('images', [
            'model' => $model,
            'image' => $image,
            'imageLang' => $imageLang
        ]);
    }

    private function findModel($id)
    {
        $model = Page::findOne($id);

        if (!$model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }

    private function findCategory($id)
    {
        $category = Category::findOne($id);

        if (!$category) {
            throw new NotFoundHttpException('CategorySoap not found.');
        }

        return $category;
    }

    public function actionDelete($id)
    {
        $category = $this->findModel($id);
        $category->delete();

        return $this->redirect(['index']);
    }
}

backend/modules/page/views/category/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\modules\page\models\Category;
use vova07\imperavi\Widget as ImperaviWidget;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

$availableParentCategories = Category::find()->joinWith('lang');
$availableParentCategories = $model->isNewRecord
    ? $availableParentCategories
    : $availableParentCategories->where(['<>', Category::tableName().'.id', $model->id]);
$availableParentCategories = $availableParentCategories->all();
?>

<div class="rubric-form">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parent_id')->dropDownList(ArrayHelper::map($availableParentCategories, 'id', 'title'), ['prompt' => '']); ?>
    <?= $form->field($modelLang, 'title') ?>
    <?= $form->field($modelLang, 'short_description')->textarea(['rows' => 3]) ?>
    <?= $form->field($modelLang, 'text')->widget(ImperaviWidget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 250,
            'plugins' => [
                'clips',
                'fullscreen'
            ],
            'imageUpload' => Url::to(['image-upload']),
            'convertDivs' => false,
            'replaceDivs' => false
        ]
    ]); ?>
    <?= $form->field($model, 'alias') ?>
    <?= $form->field($model, 'active')->dropDownList(Category::getAllActiveProperties()); ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/modules/page/views/category/_submenu.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Html;

$action = Yii::$app->controller->action->id;
?>

<h1><?= Html::encode($this->title) ?></h1>

<ul class="nav nav-tabs">
    <li <?= ($action === 'update') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['update', 'id' => $model->primaryKey]) ?>">
            Редактирование
        </a>
    </li>
    <li <?= ($action === 'seo') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['seo', 'id' => $model->primaryKey]) ?>">
            Редактирование SEO
        </a>
    </li>
</ul>
<br>

backend/modules/page/views/category/create.php
<?php

use yii\helpers\Html;

$this->title = 'Добавление категории страниц';
$this->params['breadcrumbs'][] = ['label' => 'Категории страниц', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="rubric-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelLang' => $modelLang
    ]) ?>
</div>

backend/modules/page/views/category/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use backend\modules\page\models\Category;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\page\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории страниц';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="x_panel">
    <div class="rubric-default-index">
        <h1>
            <?= $this->title; ?>
            <a href="<?= Url::to(['create']); ?>" class="btn btn-success block right">
                <i class="fa fa-plus" aria-hidden="true"></i>Добавить категорию
            </a>
        </h1>

        <?= \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                    'attribute' => 'id',
                    'contentOptions' => ['style' => 'width: 60px;']
                ],
                'title',
                'short_description',
                [
                    'attribute' => 'parent_id',
                    'filter' => ArrayHelper::map(Category::find()->joinWith('lang')->all(), 'id', 'title'),
                    'format' => 'raw',
                    'value' => function($model) {
                        $parent = $model->parent;
                        return $parent ? Html::a($parent->title, ['view', 'id' => $parent->id]) : '';
                    }
                ],
                'alias',
                [
                    'attribute' => 'active',
                    'filter' => Category::getAllActiveProperties(),
                    'value' => 'activeDetail'
                ],
                [
                    'contentOptions' => ['style'=>'width: 105px;'],
                    'format' => 'raw',
                    'value' => function ($model) {
                        return
                            Html::a('<i class="fa fa-eye"></i>',
                                ['view', 'id' => $model->primaryKey],
                                ['class' => 'btn btn-primary btn-xs', 'title' => 'Просмотреть']
                            ) . ' ' .
                            Html::a('<i class="fa fa-pencil"></i>',
                                ['update', 'id' => $model->primaryKey],
                                ['class' => 'btn btn-info btn-xs', 'title' => 'Редактировать']
                            ) . ' ' .
                            Html::a('<i class="fa fa-trash-o"></i>',
                                ['delete', 'id' => $model->primaryKey],
                                [
                                    'class' => 'btn btn-danger btn-xs',
                                    'title' => 'Удалить',
                                    'onclick' => 'return confirm("Вы уверены, что хотите удалить данную запись?")',
                                    'data-method' => 'post'
                                ]
                            );
                    }
                ],
            ],
        ]); ?>
    </div>
</div>

backend/modules/page/views/category/seo.php
<?php
use backend\widgets\SeoWidget;
$this->title = 'Редактирование SEO';
$this->params['breadcrumbs'][] = ['label' => 'Категории страниц', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Категория #'.$model->primaryKey, 'url' => ['view', 'id' => $model->primaryKey]];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="rubric-create">
    <?= $this->render('_submenu', [
        'model' => $model,
    ]); ?>

    <?= SeoWidget::widget([
        'model' => $seo,
        'modelLang' => $seoLang,
        'owner' => $model
    ]); ?>
</div>

backend/modules/page/views/category/update.php
<?php
$this->title = 'Редактирование';
$this->params['breadcrumbs'][] = ['label' => 'Категории страниц', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Категория #'.$model->primaryKey, 'url' => ['view', 'id' => $model->primaryKey]];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="rubric-create">
    <?= $this->render('_submenu', [
        'model' => $model,
        'modelLang' => $modelLang
    ]); ?>

    <?= $this->render('_form', [
        'model' => $model,
        'modelLang' => $modelLang
    ]) ?>
</div>

backend/modules/page/views/category/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use backend\modules\page\models\Page;

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Категории страниц', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="rubric-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<i class="fa fa-pencil"></i>Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('<i class="fa fa-trash-o"></i>Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить данную запись?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('<i class="fa fa-file-powerpoint-o"></i>Добавить страницу', ['page/create', 'category' => $model->id], ['class' => 'btn btn-success right']) ?>
    </p>

    <table id="w0" class="table table-striped table-bordered detail-view">
        <tbody>
        <tr>
            <th width="200px">ID</th>
            <td><?= $model->primaryKey; ?></td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('title'); ?></th>
            <td><?= $model->title; ?></td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('short_description'); ?></th>
            <td><?= $model->short_description; ?></td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('alias'); ?></th>
            <td><?= $model->alias; ?></td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('parent_id'); ?></th>
            <td>
                <?php $parent = $model->parent; ?>
                <?php if ($parent) { ?>
                    <a href="<?= Url::to(['view', 'id' => $parent->primaryKey]) ?>"><?= $parent->title; ?></a>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('subcategories'); ?></th>
            <td>
                <?php $subcategories = $model->subcategories; ?>
                <?php foreach ($subcategories as $subcategory) { ?>
                    <a href="<?= Url::to(['view', 'id' => $subcategory->primaryKey]); ?>" class="block">
                        <?= $subcategory->title; ?>
                    </a>
                <?php } ?>

                <div style="margin-top: 10px">
                    <a href="<?= Url::to(['create', 'parent' => $model->primaryKey]); ?>"
                       class="btn-sm btn-success without-hover-text-decoration"
                    >
                        <i class="fa fa-plus" aria-hidden="true" style="padding-right: 10px;"></i>Добавить подкатегорию
                    </a>
                </div>
            </td>
        </tr>
        <tr>
            <th><?= $model->getAttributeLabel('pages'); ?></th>
            <td>
                <a href="<?= Url::to(['page/index', 'category' => $model->primaryKey]); ?>">
                    <?= $model->getAttributeLabel('pages'); ?>
                    (<?= Page::find()->where(['category_id' => $model->primaryKey])->count(); ?>)
                </a>
            </td>
        </tr>
        </tbody>
    </table>
</div>